// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"
)

// LoadResponse defines model for LoadResponse.
type LoadResponse struct {
	Data SaveData `json:"data"`

	// Sig `SipHash-2-4(LOAD_SECRET, <data の raw JSON bytes>)` の lowercase hex (16文字)。
	// Udon 側で検証することでロード応答の MITM 改ざんを検知できる。
	Sig string `json:"sig"`
}

// RankingRow defines model for RankingRow.
type RankingRow struct {
	// DisplayName VRChat 表示名
	DisplayName string `json:"display_name"`

	// Rank 順位 (1 始まり)
	Rank int `json:"rank"`

	// Score スコア
	Score int64 `json:"score"`

	// UpdatedAt 最終更新日時
	UpdatedAt time.Time `json:"updated_at"`

	// Verified セーブが JWT 認証下で行われたか (= `save_history.jti IS NOT NULL`)。
	// 署名のみで保存されたエントリは `false`。
	Verified bool `json:"verified"`
}

// SaveData defines model for SaveData.
type SaveData struct {
	// GeneratedAt セーブ生成時刻 (RFC3339)。サーバ時刻に対し `-7d ～ +5min` の範囲外は
	// `/save` で `400` 拒否される。同一 display_name で同一値の重複保存は
	// `409`。
	GeneratedAt time.Time `json:"generated_at"`

	// Score スコア
	Score int64 `json:"score"`
}

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	// State OAuth state トークン
	State string `form:"state" json:"state"`

	// Code OAuth 認可コード
	Code string `form:"code" json:"code"`
}

// GetAuthPortalParams defines parameters for GetAuthPortal.
type GetAuthPortalParams struct {
	// VsrsPortalSession /auth/callback で発行されたセッショントークン
	VsrsPortalSession string `form:"vsrs_portal_session" json:"vsrs_portal_session"`
}

// AuthRegisterParams defines parameters for AuthRegister.
type AuthRegisterParams struct {
	// VsrsPortalSession /auth/callback で発行されたセッショントークン (単発使用)
	VsrsPortalSession string `form:"vsrs_portal_session" json:"vsrs_portal_session"`
}

// AuthStartParams defines parameters for AuthStart.
type AuthStartParams struct {
	// DisplayName 登録したい VRChat 表示名
	DisplayName string `form:"display_name" json:"display_name"`

	// Sig `SipHash-2-4(AUTH_SECRET, <display_name の raw bytes>)` の lowercase hex (16文字)
	Sig string `form:"sig" json:"sig"`

	// FakeDiscordId (Mock OAuth モード専用) 18 桁の数字。省略時はランダムな snowflake を生成。
	FakeDiscordId *string `form:"fake_discord_id,omitempty" json:"fake_discord_id,omitempty"`

	// FakeUsername (Mock OAuth モード専用) Discord ユーザー名の代替。省略時は `display_name` を流用。
	FakeUsername *string `form:"fake_username,omitempty" json:"fake_username,omitempty"`
}

// AuthUnregisterParams defines parameters for AuthUnregister.
type AuthUnregisterParams struct {
	// VsrsPortalSession /auth/callback で発行されたセッショントークン (単発使用)
	VsrsPortalSession string `form:"vsrs_portal_session" json:"vsrs_portal_session"`
}

// LoadDataParams defines parameters for LoadData.
type LoadDataParams struct {
	// DisplayName VRChat 表示名 (JWT を付ける場合は `display_name` クレームと一致必須)
	DisplayName string `form:"display_name" json:"display_name"`

	// Sig SipHash-2-4(LOAD_SECRET, display_name) の lowercase hex (16文字)
	Sig string `form:"sig" json:"sig"`

	// Jwt 認証 JWT。`display_name` が登録済みの場合は必須
	Jwt *string `form:"jwt,omitempty" json:"jwt,omitempty"`
}

// GetRankingParams defines parameters for GetRanking.
type GetRankingParams struct {
	// Limit 取得件数 (デフォルト 10)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Verified `true` のとき JWT 認証付きで保存されたエントリのみを返す。
	// 省略時は署名のみのエントリも含む。
	Verified *bool `form:"verified,omitempty" json:"verified,omitempty"`
}

// SaveDataParams defines parameters for SaveData.
type SaveDataParams struct {
	// DisplayName VRChat 表示名 (JWT を付ける場合は `display_name` クレームと一致必須)
	DisplayName string `form:"display_name" json:"display_name"`

	// Data `SaveData` を JSON 化したもの (URL エンコード必要)。
	Data string `form:"data" json:"data"`

	// Sig SipHash-2-4(SAVE_SECRET, data ‖ 0x00 ‖ display_name) の lowercase hex (16文字)
	Sig string `form:"sig" json:"sig"`

	// Jwt 認証 JWT。`display_name` が登録済みの場合は必須
	Jwt *string `form:"jwt,omitempty" json:"jwt,omitempty"`
}
