// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"
)

// LoadResponse defines model for LoadResponse.
type LoadResponse struct {
	Data SaveData `json:"data"`

	// Sig dataのHMAC-SHA256 署名
	Sig string `json:"sig"`
}

// RankingRow defines model for RankingRow.
type RankingRow struct {
	// DisplayName ユーザー名
	DisplayName string `json:"display_name"`

	// Rank 順位
	Rank int `json:"rank"`

	// Score スコア
	Score int64 `json:"score"`

	// UpdatedAt 最終更新日時
	UpdatedAt time.Time `json:"updated_at"`
}

// SaveData defines model for SaveData.
type SaveData struct {
	// Score スコア
	Score int64 `json:"score"`
}

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	// State OAuth state トークン
	State string `form:"state" json:"state"`

	// Code OAuth認可コード
	Code string `form:"code" json:"code"`
}

// GetAuthPortalParams defines parameters for GetAuthPortal.
type GetAuthPortalParams struct {
	// Token セッショントークン
	Token string `form:"token" json:"token"`
}

// AuthRegisterFormdataBody defines parameters for AuthRegister.
type AuthRegisterFormdataBody struct {
	// Token セッショントークン
	Token string `form:"token" json:"token"`
}

// AuthStartParams defines parameters for AuthStart.
type AuthStartParams struct {
	// Name ユーザー名
	Name string `form:"name" json:"name"`
}

// AuthUnregisterFormdataBody defines parameters for AuthUnregister.
type AuthUnregisterFormdataBody struct {
	// Token セッショントークン
	Token string `form:"token" json:"token"`
}

// LoadDataParams defines parameters for LoadData.
type LoadDataParams struct {
	// Jwt 認証JWT
	Jwt string `form:"jwt" json:"jwt"`

	// DisplayName ユーザー名(JWTのdisplay_nameクレームと一致する必要あり)
	DisplayName string `form:"display_name" json:"display_name"`

	// Sig HMAC-SHA256(display_name)の署名
	Sig string `form:"sig" json:"sig"`
}

// GetRankingParams defines parameters for GetRanking.
type GetRankingParams struct {
	// Limit 取得件数(デフォルト 10)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SaveDataParams defines parameters for SaveData.
type SaveDataParams struct {
	// Jwt 認証JWT
	Jwt string `form:"jwt" json:"jwt"`

	// DisplayName ユーザー名(JWTのdisplay_nameクレームと一致する必要あり)
	DisplayName string `form:"display_name" json:"display_name"`

	// Data セーブデータ(JSON)
	Data string `form:"data" json:"data"`

	// Sig HMAC-SHA256(data, display_name)の署名
	Sig string `form:"sig" json:"sig"`
}

// AuthRegisterFormdataRequestBody defines body for AuthRegister for application/x-www-form-urlencoded ContentType.
type AuthRegisterFormdataRequestBody AuthRegisterFormdataBody

// AuthUnregisterFormdataRequestBody defines body for AuthUnregister for application/x-www-form-urlencoded ContentType.
type AuthUnregisterFormdataRequestBody AuthUnregisterFormdataBody
