// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for PostAuthPortalFormdataBodyAction.
const (
	Register   PostAuthPortalFormdataBodyAction = "register"
	Unregister PostAuthPortalFormdataBodyAction = "unregister"
)

// Valid indicates whether the value is a known member of the PostAuthPortalFormdataBodyAction enum.
func (e PostAuthPortalFormdataBodyAction) Valid() bool {
	switch e {
	case Register:
		return true
	case Unregister:
		return true
	default:
		return false
	}
}

// LoadResponse defines model for LoadResponse.
type LoadResponse struct {
	Data SaveData `json:"data"`

	// Sig dataのHMAC-SHA256 署名
	Sig string `json:"sig"`
}

// RankingRow defines model for RankingRow.
type RankingRow struct {
	// DisplayName ユーザー名
	DisplayName string `json:"display_name"`

	// Rank 順位
	Rank int `json:"rank"`

	// Score スコア
	Score int64 `json:"score"`

	// UpdatedAt 最終更新日時
	UpdatedAt time.Time `json:"updated_at"`
}

// SaveData defines model for SaveData.
type SaveData struct {
	// Score スコア
	Score int64 `json:"score"`
}

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	// State OAuth state トークン
	State string `form:"state" json:"state"`

	// Code OAuth認可コード
	Code string `form:"code" json:"code"`
}

// GetAuthPortalParams defines parameters for GetAuthPortal.
type GetAuthPortalParams struct {
	// Token セッショントークン
	Token string `form:"token" json:"token"`
}

// PostAuthPortalFormdataBody defines parameters for PostAuthPortal.
type PostAuthPortalFormdataBody struct {
	// Action 実行するアクション
	Action PostAuthPortalFormdataBodyAction `form:"action" json:"action"`

	// Token セッショントークン
	Token string `form:"token" json:"token"`
}

// PostAuthPortalFormdataBodyAction defines parameters for PostAuthPortal.
type PostAuthPortalFormdataBodyAction string

// AuthStartParams defines parameters for AuthStart.
type AuthStartParams struct {
	// Name ユーザー名
	Name string `form:"name" json:"name"`
}

// LoadDataParams defines parameters for LoadData.
type LoadDataParams struct {
	// Jwt 認証JWT
	Jwt string `form:"jwt" json:"jwt"`
}

// GetRankingParams defines parameters for GetRanking.
type GetRankingParams struct {
	// Limit 取得件数（デフォルト 10）
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SaveDataParams defines parameters for SaveData.
type SaveDataParams struct {
	// Jwt 認証JWT
	Jwt string `form:"jwt" json:"jwt"`

	// Data セーブデータ
	Data string `form:"data" json:"data"`

	// Sig dataのHMAC-SHA256署名
	Sig string `form:"sig" json:"sig"`
}

// PostAuthPortalFormdataRequestBody defines body for PostAuthPortal for application/x-www-form-urlencoded ContentType.
type PostAuthPortalFormdataRequestBody PostAuthPortalFormdataBody
